# Generated by Django 5.2.7 on 2025-11-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
